// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NumuneKabul.Infrastructure.Data;

#nullable disable

namespace NumuneKabul.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706111011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("NumuneKabul.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.ExtractedField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<int>("PageNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PdfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Width")
                        .HasColumnType("REAL");

                    b.Property<double?>("X")
                        .HasColumnType("REAL");

                    b.Property<double?>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PdfId");

                    b.ToTable("ExtractedFields");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.FormTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.IntegrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("PdfId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PdfId");

                    b.ToTable("IntegrationJobs");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.OcrResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PdfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PdfId");

                    b.ToTable("OcrResults");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.PdfDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PdfDocuments");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.TemplateField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Regex")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "FieldName")
                        .IsUnique();

                    b.ToTable("TemplateFields");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.XmlArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PdfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("XmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PdfId");

                    b.ToTable("XmlArchives");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.ExtractedField", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.PdfDocument", "PdfDocument")
                        .WithMany("ExtractedFields")
                        .HasForeignKey("PdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdfDocument");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.FormTemplate", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.Institution", "Institution")
                        .WithMany("FormTemplates")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.IntegrationJob", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.PdfDocument", "PdfDocument")
                        .WithMany("IntegrationJobs")
                        .HasForeignKey("PdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdfDocument");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.OcrResult", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.PdfDocument", "PdfDocument")
                        .WithMany("OcrResults")
                        .HasForeignKey("PdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdfDocument");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.PdfDocument", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NumuneKabul.Domain.Entities.FormTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Institution");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.TemplateField", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.FormTemplate", "Template")
                        .WithMany("TemplateFields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.XmlArchive", b =>
                {
                    b.HasOne("NumuneKabul.Domain.Entities.PdfDocument", "PdfDocument")
                        .WithMany("XmlArchives")
                        .HasForeignKey("PdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdfDocument");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.FormTemplate", b =>
                {
                    b.Navigation("TemplateFields");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.Institution", b =>
                {
                    b.Navigation("FormTemplates");
                });

            modelBuilder.Entity("NumuneKabul.Domain.Entities.PdfDocument", b =>
                {
                    b.Navigation("ExtractedFields");

                    b.Navigation("IntegrationJobs");

                    b.Navigation("OcrResults");

                    b.Navigation("XmlArchives");
                });
#pragma warning restore 612, 618
        }
    }
}
